import './globals.css'
import Menu from '@/app/menu.jsx'
import { Noto_Sans_JP } from 'next/font/google'

const notoSansJP = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/line-seed-jp/line-seed-jp.css" />
      </head>
      <body className={notoSansJP.variable}>
        <Menu />
        <div id="main-content">
          {children}
        </div>
      </body>
    </html>
  )
}
