import "./globals.css";
import Header from "@/app/compoent/header";
import { M_PLUS_2, Noto_Sans_JP } from "next/font/google";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

const mPlus2 = M_PLUS_2({
  variable: "--font-m-plus2",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={`${mPlus2.variable} ${notoSansJP.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
